export enum ROOT {
  SETS = 'ROOT_SETS',
  WINDOW_WIDTH = 'ROOT_WINDOW_WIDTH',

  INITIALIZE_SETS = 'ROOT_INITIALIZE_SETS',
}

export enum DECKLIST {
  TITLE = 'DECKLIST_TITLE',
  ADD_CARD = 'DECKLIST_ADD_CARD',
  REMOVE_CARD = 'DECKLIST_REMOVE_CARD',
}

export enum SEARCH {
  LOAD = 'SEARCH_LOAD',
  SUCCESS = 'SEARCH_SUCCESS',
  FAILURE = 'SEARCH_FAILURE',
  NAME = 'SEARCH_NAME',
  SETS = 'SEARCH_SETS',
  TYPES = 'SEARCH_TYPES',
  SUBTYPES = 'SEARCH_SUBTYPES',
  SUPERTYPES = 'SEARCH_SUPERTYPES',

  REQUEST = 'SEARCH_REQUEST',
}
