export enum ROOT {
  SETS = 'ROOT_SETS',
  TYPES = 'ROOT_TYPES',
  SUBTYPES = 'ROOT_SUBTYPES',
  SUPERTYPES = 'ROOT_SUPERTYPES',

  INITIALIZE_SETS = 'ROOT_INITIALIZE_SETS',
  INITIALIZE_TYPES = 'ROOT_INITIALIZE_TYPES',
  INITIALIZE_SUBTYPES = 'ROOT_INITIALIZE_SUBTYPES',
  INITIALIZE_SUPERTYPES = 'ROOT_INITIALIZE_SUPERTYPES',
}

export enum DECKLIST {
  ADD_CARD = 'DECKLIST_ADD_CARD',
  REMOVE_CARD = 'DECKLIST_REMOVE_CARD',
}

export enum SEARCH {
  LOAD = 'SEARCH_LOAD',
  SUCCESS = 'SEARCH_SUCCESS',
  FAILURE = 'SEARCH_FAILURE',
  NAME = 'SEARCH_NAME',

  REQUEST = 'SEARCH_REQUEST',
}
