/* tslint:disable */
import './chevron'
import './Colorless'
import './Darkness'
import './Dragon'
import './Fairy'
import './Fighting'
import './Fire'
import './Grass'
import './hamburger'
import './Lightning'
import './Metal'
import './minus'
import './plus'
import './Psychic'
import './Water'
